### ISSUE TITLE
Rounding exchange rate

### ISSUE THREAD

**Issue by gtim** [SandorTeleki/inspiredvanillawebprojects#1]
Neat adaptations! I'm not well-versed in finance, but perhaps it would make sense to round the exchange rate to some number of significant digits instead of displaying attopounds?

![image](https://github.com/SandorTeleki/inspiredvanillawebprojects/assets/1546926/9453a2cf-f258-424b-91bb-846565c73bbb)

**Comment by SandorTeleki** [comment]
Thanks! Hmm, yeah, I think that could be an easy/quick fix. The swap rate is just what the API returned. I'll add a toFixed to the swap rate, which should solve this issue.

**Comment by SandorTeleki** [comment]
Fixed in commit: [86fab58](https://github.com/SandorTeleki/inspiredvanillawebprojects/commit/86fab58dde21fdce6752fb8d57648ea3cbf4ea3a)

**Comment by SandorTeleki** [comment]
Fixed in commit: [86fab58](https://github.com/SandorTeleki/inspiredvanillawebprojects/commit/86fab58dde21fdce6752fb8d57648ea3cbf4ea3a)
